=== stringbean1968/Literature/BusinessLists/Veterinarians/JSONData/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/stringbean1968/Literature/blob/main/BusinessLists/Veterinarians/JSONData/schema.json",
  "title": "UK Veterinary Practice",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "practiceName",
      "town",
      "postcode",
      "country",
      "lastVerified"
    ],
    "properties": {
      "id": {
        "type": "string",
        "description": "Globally unique slug identifier"
      },
      "practiceName": {
        "type": "string"
      },
      "tradingName": {
        "type": [
          "string",
          "null"
        ]
      },
      "parentGroup": {
        "type": [
          "string",
          "null"
        ]
      },
      "practiceType": {
        "type": "string",
        "enum": [
          "Small Animal",
          "Equine",
          "Farm Animal",
          "Mixed Practice",
          "Exotic Animal",
          "Referral Hospital",
          "Emergency",
          "Mobile Vet",
          "Small Animal & Exotic",
          "Companion Animal"
        ]
      },
      "species": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "services": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "rcvsPracticeNumber": {
        "type": [
          "string",
          "null"
        ]
      },
      "rcvsAccreditation": {
        "type": [
          "string",
          "null"
        ]
      },
      "addressLine1": {
        "type": [
          "string",
          "null"
        ]
      },
      "addressLine2": {
        "type": [
          "string",
          "null"
        ]
      },
      "town": {
        "type": "string"
      },
      "county": {
        "type": [
          "string",
          "null"
        ]
      },
      "postcode": {
        "type": "string",
        "pattern": "^[A-Z]{1,2}[0-9][0-9A-Z]? ?[0-9][A-Z]{2}$"
      },
      "country": {
        "type": "string",
        "enum": [
          "England",
          "Scotland",
          "Wales",
          "Northern Ireland"
        ]
      },
      "region": {
        "type": [
          "string",
          "null"
        ]
      },
      "latitude": {
        "type": [
          "number",
          "null"
        ]
      },
      "longitude": {
        "type": [
          "number",
          "null"
        ]
      },
      "phone": {
        "type": [
          "string",
          "null"
        ]
      },
      "alternatePhone": {
        "type": [
          "string",
          "null"
        ]
      },
      "emergencyPhone": {
        "type": [
          "string",
          "null"
        ]
      },
      "email": {
        "type": [
          "string",
          "null"
        ]
      },
      "website": {
        "type": [
          "string",
          "null"
        ]
      },
      "openingHours": {
        "type": [
          "object",
          "null"
        ]
      },
      "outOfHoursProvider": {
        "type": [
          "string",
          "null"
        ]
      },
      "socialMedia": {
        "type": [
          "object",
          "null"
        ]
      },
      "companiesHouseNumber": {
        "type": [
          "string",
          "null"
        ]
      },
      "vatNumber": {
        "type": [
          "string",
          "null"
        ]
      },
      "principalVet": {
        "type": [
          "string",
          "null"
        ]
      },
      "clinicalDirector": {
        "type": [
          "string",
          "null"
        ]
      },
      "numberOfVets": {
        "type": [
          "number",
          "null"
        ]
      },
      "dateEstablished": {
        "type": [
          "string",
          "null"
        ]
      },
      "notes": {
        "type": [
          "string",
          "null"
        ]
      },
      "sources": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "lastVerified": {
        "type": "string",
        "format": "date"
      }
    },
    "additionalProperties": false
  }
}

=== stringbean1968/Literature/BusinessLists/Veterinarians/JSONData/practices/K/Vets_K.json
[
  {
    "id": "kate-field-veterinary-group-1085",
    "practiceName": "Kate Field Veterinary Group",
    "tradingName": null,
    "parentGroup": "Highcroft Veterinary Group",
    "practiceType": "Emergency",
    "species": [
      "Dogs",
      "Cats",
      "Rabbits",
      "Small Mammals",
      "Birds"
    ],
    "services": [
      "Hydrotherapy",
      "Physiotherapy",
      "Acupuncture",
      "Rehabilitation"
    ],
    "rcvsPracticeNumber": "7943999",
    "rcvsAccreditation": null,
    "addressLine1": "132 Princess Road",
    "addressLine2": "Business Park",
    "town": "Oldham",
    "county": "Greater Manchester",
    "postcode": "AB51 1ES",
    "country": "England",
    "region": "North West",
    "latitude": 53.571013,
    "longitude": -2.116594,
    "phone": "02038 677895",
    "alternatePhone": null,
    "emergencyPhone": null,
    "email": "enquiries@hotmail.co.uk",
    "website": "https://www.katefieldveterinaryg.com",
    "openingHours": {
      "monday": "08:30-18:30",
      "tuesday": "08:30-18:30",
      "wednesday": "08:30-18:30",
      "thursday": "08:30-18:30",
      "friday": "08:30-18:30",
      "saturday": "09:00-13:00"
    },
    "outOfHoursProvider": null,
    "socialMedia": null,
    "companiesHouseNumber": null,
    "vatNumber": "GB324642000",
    "principalVet": "David Clark BVSc MRCVS",
    "clinicalDirector": null,
    "numberOfVets": null,
    "dateEstablished": null,
    "notes": null,
    "sources": [
      "https://www.vets4pets.com/find-a-vet/",
      "OSM-amenity=veterinary",
      "RCVS-FindAVet",
      "Yell.com",
      "BVA-MemberDirectory"
    ],
    "lastVerified": "2023-05-09"
  },
  {
    "id": "kate-park-vet-clinic-1099",
    "practiceName": "Kate Park Vet Clinic",
    "tradingName": null,
    "parentGroup": null,
    "practiceType": "Small Animal & Exotic",
    "species": [
      "Dogs",
      "Cats",
      "Horses",
      "Cattle",
      "Sheep"
    ],
    "services": [
      "Emergency Care",
      "Surgery",
      "Oncology",
      "Orthopaedics",
      "Internal Medicine"
    ],
    "rcvsPracticeNumber": null,
    "rcvsAccreditation": null,
    "addressLine1": "41 Park Road",
    "addressLine2": null,
    "town": "Coatbridge",
    "county": "North Lanarkshire",
    "postcode": "TR1 6ZG",
    "country": "Scotland",
    "region": "Scotland",
    "latitude": 55.837331,
    "longitude": -4.021129,
    "phone": "01522 233108",
    "alternatePhone": "01727 854805",
    "emergencyPhone": null,
    "email": "info@kateparkvetclinicveterinary.co.uk",
    "website": null,
    "openingHours": null,
    "outOfHoursProvider": null,
    "socialMedia": {
      "facebook": "https://www.facebook.com/kateparkvetclinicvets",
      "instagram": "https://www.instagram.com/kateparkvetclinicvets"
    },
    "companiesHouseNumber": "95331468",
    "vatNumber": "GB931249615",
    "principalVet": null,
    "clinicalDirector": "Fiona Allen BVetMed MRCVS",
    "numberOfVets": null,
    "dateEstablished": "2001",
    "notes": null,
    "sources": [
      "Companies-House",
      "OSM-amenity=veterinary",
      "https://www.cvsvets.com/find-a-vet/",
      "RCVS-FindAVet"
    ],
    "lastVerified": "2024-05-24"
  },
  {
    "id": "keighley-vets-1062",
    "practiceName": "Keighley Vets",
    "tradingName": null,
    "parentGroup": null,
    "practiceType": "Small Animal & Exotic",
    "species": [
      "Cattle",
      "Sheep",
      "Pigs",
      "Goats"
    ],
    "services": [
      "Equine Dentistry",
      "Farriery Referrals",
      "Lameness Investigation",
      "Pre-purchase Examinations"
    ],
    "rcvsPracticeNumber": null,
    "rcvsAccreditation": null,
    "addressLine1": "193 Albert Road",
    "addressLine2": "Industrial Estate",
    "town": "Boston",
    "county": "Lincolnshire",
    "postcode": "SL1 5NU",
    "country": "England",
    "region": "East Midlands",
    "latitude": 52.945914,
    "longitude": -0.055531,
    "phone": "01823 785457",
    "alternatePhone": null,
    "emergencyPhone": null,
    "email": null,
    "website": "https://www.keighleyvets.vet",
    "openingHours": {
      "monday": "08:30-18:30",
      "tuesday": "08:30-18:30",
      "wednesday": "08:30-18:30",
      "thursday": "08:30-18:30",
      "friday": "08:30-18:30"
    },
    "outOfHoursProvider": "Local Emergency Vet",
    "socialMedia": null,
    "companiesHouseNumber": "95594067",
    "vatNumber": null,
    "principalVet": null,
    "clinicalDirector": null,
    "numberOfVets": null,
    "dateEstablished": null,
    "notes": null,
    "sources": [
      "https://www.vets4pets.com/find-a-vet/",
      "Google-Places",
      "OSM-amenity=veterinary",
      "RCVS-FindAVet",
      "BVA-MemberDirectory"
    ],
    "lastVerified": "2023-11-16"
  },
  {
    "id": "keighley-village-veterinary-services-1100",
    "practiceName": "Keighley Village Veterinary Services",
    "tradingName": null,
    "parentGroup": null,
    "practiceType": "Equine",
    "species": [
      "Dogs",
      "Cats",
      "Rabbits",
      "Reptiles",
      "Exotic Animals"
    ],
    "services": [
      "Emergency Care",
      "Surgery",
      "Oncology",
      "Orthopaedics",
      "Internal Medicine"
    ],
    "rcvsPracticeNumber": "7437234",
    "rcvsAccreditation": "Practice Standards Scheme - Advanced",
    "addressLine1": "89 Chapel Street",
    "addressLine2": null,
    "town": "Exeter",
    "county": "Devon",
    "postcode": "LA1 9EL",
    "country": "England",
    "region": "South West",
    "latitude": null,
    "longitude": null,
    "phone": "01752 577180",
    "alternatePhone": "01978 749223",
    "emergencyPhone": "01424 665285",
    "email": "enquiries@outlook.com",
    "website": "https://www.keighleyvillageveter.vet",
    "openingHours": null,
    "outOfHoursProvider": "Vets Now",
    "socialMedia": {
      "instagram": "https://www.instagram.com/keighleyvillagevetervets"
    },
    "companiesHouseNumber": "47326499",
    "vatNumber": null,
    "principalVet": null,
    "clinicalDirector": "Daniel Clarke BVetMed MRCVS",
    "numberOfVets": 15,
    "dateEstablished": "2002",
    "notes": null,
    "sources": [
      "https://www.ivcevidensia.co.uk/find-a-vet/",
      "OSM-amenity=veterinary",
      "RCVS-FindAVet",
      "VMD-RegisteredPremises",
      "Yell.com"
    ],
    "lastVerified": "2023-01-19"
  },
  {
    "id": "kelso-mill-veterinary-services-1079",
    "practiceName": "Kelso Mill Veterinary Services",
    "tradingName": null,
    "parentGroup": null,
    "practiceType": "Mixed Practice",
    "species": [
      "Cattle",
      "Sheep",
      "Pigs",
      "Goats",
      "Horses"
    ],
    "services": [
      "Consultations",
      "Vaccinations",
      "Neutering",
      "Microchipping",
      "Pet Health Plans"
    ],
    "rcvsPracticeNumber": "7430504",
    "rcvsAccreditation": null,
    "addressLine1": "186 Market Street",
    "addressLine2": "Unit 8",
    "town": "Truro",
    "county": "Cornwall",
    "postcode": "DT1 7UU",
    "country": "England",
    "region": "South West",
    "latitude": 50.232189,
    "longitude": -5.015654,
    "phone": "01264 428318",
    "alternatePhone": null,
    "emergencyPhone": null,
    "email": "hello@kelsomillveterinarysveterinary.co.uk",
    "website": null,
    "openingHours": {
      "monday": "08:30-18:30",
      "tuesday": "08:30-18:30",
      "wednesday": "08:30-18:30",
      "thursday": "08:30-18:30",
      "friday": "08:30-18:30",
      "saturday": "09:00-13:00"
    },
    "outOfHoursProvider": null,
    "socialMedia": null,
    "companiesHouseNumber": "40813626",
    "vatNumber": null,
    "principalVet": null,
    "clinicalDirector": null,
    "numberOfVets": 7,
    "dateEstablished": "1995",
    "notes": null,
    "sources": [
      "OSM-amenity=veterinary",
      "Yell.com",
      "RCVS-FindAVet"
    ],
    "lastVerified": "2023-03-25"
  },
  {
    "id": "kelso-veterinary-clinic-1063",
    "practiceName": "Kelso Veterinary Clinic",
    "tradingName": null,
    "parentGroup": null,
    "practiceType": "Emergency",
    "species": [
      "Horses",
      "Ponies"
    ],
    "services": [
      "Equine Dentistry",
      "Farriery Referrals",
      "Lameness Investigation",
      "Pre-purchase Examinations"
    ],
    "rcvsPracticeNumber": "7501409",
    "rcvsAccreditation": null,
    "addressLine1": "42 Park Road",
    "addressLine2": "Industrial Estate",
    "town": "High Wycombe",
    "county": "Buckinghamshire",
    "postcode": "TW1 9DW",
    "country": "England",
    "region": "South East",
    "latitude": 51.584384,
    "longitude": -0.761455,
    "phone": "01724 920085",
    "alternatePhone": null,
    "emergencyPhone": null,
    "email": null,
    "website": null,
    "openingHours": null,
    "outOfHoursProvider": null,
    "socialMedia": null,
    "companiesHouseNumber": "23681900",
    "vatNumber": "GB553514543",
    "principalVet": "Tim Mitchell BVSc MRCVS",
    "clinicalDirector": null,
    "numberOfVets": null,
    "dateEstablished": null,
    "notes": null,
    "sources": [
      "OSM-amenity=veterinary",
      "https://www.medivet.co.uk/find-a-vet/",
      "RCVS-FindAVet"
    ],
    "lastVerified": "2024-12-03"
  },
  {
    "id": "kendal-pet-hospital-1076",
    "practiceName": "Kendal Pet Hospital",
    "tradingName": null,
    "parentGroup": null,
    "practiceType": "Small Animal",
    "species": [
      "Cattle",
      "Sheep",
      "Pigs",
      "Goats"
    ],
    "services": [
      "Farm Health Planning",
      "Fertility Testing",
      "Caesarean",
      "TB Testing"
    ],
    "rcvsPracticeNumber": "7298656",
    "rcvsAccreditation": null,
    "addressLine1": "23 Church Street",
    "addressLine2": null,
    "town": "Dover",
    "county": "Kent",
    "postcode": "WR1 5XZ",
    "country": "England",
    "region": "South East",
    "latitude": null,
    "longitude": null,
    "phone": "01202 720784",
    "alternatePhone": null,
    "emergencyPhone": null,
    "email": null,
    "website": "https://www.kendalpethospital.vet",
